#!/bin/bash

## EXECUTE

clock -s -i 45 -f "%A, %B %eth %I:%M %p" | \
while read clock
	set clock (echo $clock | sed s/\ \ /\ /)
	echo "%{c}%{A:bash $HOME/.lemonbar/popups/clock/clock &:}$clock%{A}"
end
