#!/bin/bash

## EXECUTE

# Exit if open
if test (pgrep -f "n30f -d -x 870" | head -n 1)
	pkill -n -f "n30f -d -x 870"
	pkill -f "n30f -d -x 857"
	pkill -f "lemonbar -g 168x20"
	exit
end

set -x font -artwiz-cure-medium-r-normal--11-110-75-75-p-90-iso8859-1
set -x fg 021B21
set -x bg EEEEEE

n30f -d -x 870 -y 914 $HOME/.lemonbar/popups/clock/bg.png &

raingraph /tmp/raingraph.png
n30f -d -x 857 -y 991 /tmp/raingraph.png &
bash $HOME/.lemonbar/popups/clock/celsius | lemonbar -g 168x20+872+74 -b -p -d -f $font -B \#00$bg -F \#$fg &
bash $HOME/.lemonbar/popups/clock/moon | lemonbar -g 168x20+872+250 -b -p -d -f $font -B \#00$bg -F \#$fg &
